### ISSUE TITLE
configure your repository to block merging to `main` until ContinuousIntegration (CI) checks have passed

### ISSUE THREAD

**Issue by zerubabel4** [lab-brussels-1/home#151]

**Comment by samirm00** [comment]
Hello @zerubabel4, why do you have two issues? one is enough and you can change the title to be similar to your colleagues.

**Comment by zerubabel4** [comment]
O okay mr.samirm00 i will fix it now

**Comment by samirm00** [comment]
@zerubabel4  Great! please don't call me `mr` ,  Samir is good.

**Comment by zerubabel4** [comment]
sure 😁
