### ISSUE TITLE
Marie Josee: Workflows, 2 weeks

### ISSUE THREAD

**Issue by Ufitamahoro** [lab-brussels-1/home#180]
# Week 1

## What went well?
I get helped by Tamer and Samir, I got to learn what my mistakes are.

## What went less well?
It was confusing.

## Lessons Learned
- To reach out, network. 
- Linting
- Pull and push 

## Sunday Prep Work
- I am going to start

**Comment by danielhalasz** [comment]
@Ufitamahoro the check-in issue is intended to help keep track of your study progress within each module, and then each week you can add the corresponding label (now it is `week-1`) to the issue. So there is only one check-in issue per person per module. Within the check-in issue, you should list all the study material that you will go through and gradually tick off the boxes once you complete them, so we see what you have already completed and help accordingly. 
Can you please explain what was confusing this week?
