### ISSUE TITLE
Kiishi: Workflow, week 2

### ISSUE THREAD

**Issue by kiishiakande** [lab-brussels-1/home#199]
- Setup: GitHub
  - [x] created this issue
  - [x] assigned myself
  - [ ] moved the issue to the project board
- Setup: local
  - [x] pulled the most recent code from `main`/`master`
  - [x] created a new branch for my introduction
- Writing the content:
  - [x] added my intro file in `/people` according to group conventions
  - [ ] linked to my file from `/README.md` according to group conventions
- Before pushing my branch:
  - [x] formatted the code
  - [x] fixed all spelling mistakes and added new words to the dictionary
  - [x] fixed all linting mistakes
- After pushing my branch:
  - [ ] created a new PR linked to this issue
  - [ ] make sure all of the checks passed
  - [ ] assigned someone to review and merge my PR

**Comment by danielhalasz** [comment]
@kiishiakande no need to create a new issue, just add the comment to your previous one..see my post on Discord..I am closing this now..thx
