### ISSUE TITLE
Yea Sung Kim, work flow week2 

### ISSUE THREAD

**Issue by yeasung240** [lab-brussels-1/home#201]
> [my fork of module repository]()

## Learning Objectives
- Setup: GitHub
  - [x] created this issue
  - [x] assigned myself
  - [ ] moved the issue to the project board
- Setup: local
  - [ ] pulled the most recent code from `main`/`master`
  - [ ] created a new branch for my introduction
- Writing the content:
  - [ ] added my intro file in `/people` according to group conventions
  - [ ] linked to my file from `/README.md` according to group conventions
- Before pushing my branch:
  - [ ] formatted the code
  - [ ] fixed all spelling mistakes and added new words to the dictionary
  - [ ] fixed all linting mistakes
- After pushing my branch:
  - [ ] created a new PR linked to this issue
  - [ ] make sure all of the checks passed
  - [ ] assigned someone to review and merge my PR

**Comment by danielhalasz** [comment]
@yeasung240 no need to create a new issue, just add the comment to your previous one..see my post on Discord..I am closing this now..thx
