### ISSUE TITLE
Dnyandeo : Workflow week 2

### ISSUE THREAD

**Issue by Dnyandeo33** [lab-brussels-1/home#203]
- Setup: GitHub
  - [x] created this issue
  - [x] assigned myself
  - [x] moved the issue to the project board
- Setup: local
  - [x] pulled the most recent code from `main`/`master`
  - [x] created a new branch for my introduction
- Writing the content:
  - [x] added my intro file in `/people` according to group conventions
  - [ ] linked to my file from `/README.md` according to group conventions
- Before pushing my branch:
  - [x] formatted the code
  - [x] fixed all spelling mistakes and added new words to the dictionary
  - [x] fixed all linting mistakes
- After pushing my branch:
  - [x] created a new PR linked to this issue
  - [x] make sure all of the checks passed
  - [x] assigned someone to review and merge my PR

**Comment by Dnyandeo33** [comment]
## What went well?
- [x] I studied how to `pull` and `push` code using Git & Github.
- [x] Worked with `team`.
- [x] `Reviewed` Pull request.
- [x] `Merged` branch to `main`.
- [x] `Assigned` pull request to `contributor`. 
- [x] Understood `project management`.
- [x] Learned how to use `project board`.

## What went less well?
I didn't work on `project setup` by myself. that's why, I did not understand well. How to create project profile? But i'm tying to understand with my team.

## Lessons Learned
    Now i'm confident about Git and Github. I learned basic command of Git. And how to use it for project management.  

## Sunday Prep Work
Learning `HTML` and `CSS`

**Comment by danielhalasz** [comment]
@Dnyandeo33 no need to create a new issue, just add the comment to your previous one..see my post on Discord..I am closing this now..thx

**Comment by Dnyandeo33** [comment]
Sorry @danielhalasz I just saw your comments. Thank you.
