### ISSUE TITLE
Elias: Workflows week 2

### ISSUE THREAD

**Issue by EliasMlopez99** [lab-brussels-1/home#207]
Week 2

- [x] I have pushed my progress to [my fork of exercises repo](_)

## I Need Help With:
So far everything is clear with the exception of how to control the size of an image when you use the following code
`![alt text for your image](/path/to/image.png)` I would like to know how do you do it.
## What went well?
Pulling a request, git pulling and git pushing, and running the `npm` commands in order to check my codification 
## What went less well?
the `cspell.json` it has been a problem since the beginning, though I could upload my file because I ran the rpm commands, I needed first add words to this section to avoid conflicts with my files.
## Lessons Learned

1. I know where I am know, I have been practicing a lot by myself and did a lot of mistakes but now is more clear, practicing helps more than reading.   
2. I fully understand how `npm` works and how to run the commands in a logic sequence.
3. I now know that in order to avoid conflicts with the spell check I have to update our `spell.json` 

 #Sunday Prep Work
Preparing myself studying and watching material related to HTML codification.

**Comment by danielhalasz** [comment]
@EliasMlopez99 you only need 1 check-in issue per module, as had been discussed. please put the above comment in your previous issue as a new comment. I will close this now.

**Comment by danielhalasz** [comment]
also, you only add the `check-in` and `week-x` labels..we add the `checked-x` label, once we respond to it 🙂
