### ISSUE TITLE
Minju: Agile Development, 4 weeks

### ISSUE THREAD

**Issue by minjupgeorge** [lab-brussels-1/home#228]
## [0. Developing HTML & CSS](./0-developing-html-and-css)

Practice with the skills, tools, and workflows you will need to efficiently
develop websites written with HTML & CSS.

- 🥚 **VSCode**: you can ...
  - [x] use the _LiveServer extension_ to launch an HTML page in the browser
  - [x] use autocomplete to begin a new HTML document, create new tags, and much
        more
  - [x] use the _HTML CSS Support_ and _IntelliSense fo CSS class names_
        extensions to make writing HTML & CSS more efficient
- 🥚 **Formatting HTML & CSS**: You can ...
  - [x] use VSCode configurations to format your code on save
  - [x] use `npm run format` to format all the code in your repository
- [x] 🥚 **Linting CSS**: You can use the `npm run lint:css` script to find
      mistakes in your CSS, and you can fix the mistakes.
- [x] 🥚 **Validating HTML**: You can use the `npm run validate:html` script to
      find mistakes in your CSS, and you can fix the mistakes.
- 🥚 **Browser Developer Tools**: You can ...
  - [x] inspect the source code of a web page using the Sources tab
  - [x] find any part of the web page in the Elements tab of your Dev Tools DOM
        inspector
  - [x] find the styles for any element in the Elements tab
  - [x] make temporary changes in a web page from the Elements tab to see how
        they will look

## [1. Following Plans](./1-following-plans)

Practice working together in a group to build small websites in incremental
steps according to a plan. You will be given final code, a detailed plan to
rebuild it, and will need to work as a group following the processes in
[Planning and Collaborating](https://github.com/HackYourFutureBelgium/planning-and-collaborating).

- [x] 🥚 **Project Definition and Scope**: As a group, you can agree on what you
      are trying to build, and can clearly describe the project using a README
      and a repository description.
- 🥚 **Project Constraints**: As a group you can define project constraints by
  discussing your strengths, weaknesses and context. You can set these types of
  constraints:
  - [x] _External_: constraints that come from outside your group
  - [x] _Internal, Involuntary_: constraints that come from within your group,
        but your group did not decide to have.
  - [x] _Internal, Voluntary_: constraints your group decides on to improve the
        quality of your development process and final software.
- [x] 🥚 **Communication Plans**: You can work with your group mates to agree on
      a communication plan to follow during development.
- [x] 🥚 **Communicating Challenges**: During development you can discuss with
      your group when ...
  - you are blocked and need help the agreed channels of communication.
  - your schedule or availability changes
  - you are having trouble getting along with each other
- [x] 🥚 **Using a Backlog**: You can develop from a backlog of features
      organized by priority:
  - _must-have_
  - _should-have_
  - _could-have_
- [x] 🥚 **Follow a Development Strategies**: You can follow a development
      strategy to understand the code required for _must-have_ user stories.
- [x] 🥚 **Create Issues From a Dev Strategy**: You can create issues for user
      stories in your project based on the development strategy.
- 🥚 **Retrospective**: Your group can complete a retrospective to ...
  - [x] assess how well you worked as a group
  - [x] find ways to improve in the next project
  - [x] compare your plan to the reality of developing your website
- 🐣 **Claiming and Completing Issues**: You can claim issues from the _TODO_
  column of a project board and ...
  - [x] track your progress with the project board
  - [x] develop your code locally on a separate branch
  - [x] send a PR that passes CI checks and meets the requirements
- [x] 🐣 **Code Review**: You can both review a group mate's PR, and
      productively participate in a review of your own code.
- [x] 🐣 **Match a Design & Acceptance Criteria**: When developing your tasks,
      you can write code that matches the project's Wireframe and meets your
      issue's Acceptance Criteria.

## [2. Writing Plans](./2-writing-plans)

Practicing writing your own plans as a group. You will be given _only_ the final
code for HTML/CSS web pages, your group will need write a detailed plan for
rebuilding the website in small steps.

- [x] 🥚 **Write User Personas**: As a group you can describing your site's
      users with User Personas, and you can use the personas to plan your
      website from the user's perspective.
- [x] 🥚 **Write User Stories**: Given a working web page, you can describe it
      with user stories and acceptance criteria for each user story.
- [x] 🐣 **Write a Backlog**: After listing all the user stories for a web page,
      you can organize them into a Backlog by priority: _must-have_,
      _should-have_ and _could-have_
- [x] 🐣 **Create a Prioritized Design**: Using your backlog and the original
      site as a guide, you can create a Wireframe of the site your group will
      build. You can use different colors and comments to indicate a priority
      for each component in the Wireframe.
- [x] 🐣 **Write a Development Strategies**: You can translate your Wireframe
      and Backlog into a Development Strategy for the _must-have_ user stories.

## [3. Adapting Plans](./3-adapting-plans)

Even the best plans are not perfect, it's not possible to know everything ahead
of time! You may be able to plan everything ahead of time when the web pages you
build are very small and you have the code ahead of time, but it's a whole
different thing when you need to build a larger web page over a longer period of
time.

In this chapter you will practice full Agile Development by developing a larger,
open-ended web pages and adapting your plans as you go. Your team will need to
make an initial plan, but the plan will change! Practice having regular meetings
with your group to review the website's progress, review your plan, and make any
changes in the plan that are necessary to keep the project on schedule.

- [x] 🐣 **Adjusting the Backlog**: As a group you can agree to changes in the
      backlog when necessary.
- [x] 🐣 **Adjusting the Design**: As a group you can agree on changes to the
      design during the development process when it becomes clear your old
      design needs updating.
- [x] 🐣 **Updating the Project Board**: You can manage the project board by
      adding, removing or updating issues when necessary. This includes changing
      labels, milestones, or assignees when necessary.

[TOP](#agile-development)

---

**Comment by minjupgeorge** [comment]
# Week 1

## I Need Help With:

To make understand the project goal to every team member would have helped much better.

## What went well?

Planning and communication within the team.
well arranged /planning folder
Team Meetings
Review done by Team Leader @MMikhailova  is really appreciative . It helps me to have a better idea regarding the development strategy. 
Html and Css Coding.

## What went less well?

Project goal was not clear. Had difficulty in the development-strategy. but finally as a team, we resolved it.

## Lessons Learned

Communication plan must be accurate. Then everyone can attend the meeting.  Establishing specific work to each member will make task easier.
Each team member must create issue before he/she starts work and it must be visible from the project board.

## Sunday Prep Work

hopefully will start soon

**Comment by colevandersWands** [comment]
> To make understand the project goal to every team member would have helped much better.

would you have liked more help from us at the beginning, or was it more about communication in your group?

**Comment by danielhalasz** [comment]
@minjupgeorge what do you mean by the project goal? the description of the deliverable or the goal that you decided as a team?

**Comment by minjupgeorge** [comment]
Hi @colevandersWands , @danielhalasz ...
  
    YES. It is  clearly written in the deliverable that we need to rebuild the "All about Trees" website. still I don't know everyone had confusion in our group because of that we need to change development strategy many times. Even when we look into other groups website it was entirely different from the expected one. May be its because of our communication in the group .

**Comment by colevandersWands** [comment]
@minjupgeorge , it's ok if the websites are different from the original one. what's important now is figuring out how to work as a group.

And it's also 100% ok if a development strategy changes as you go, it's actually a good thing!  it means your group is able to adapt as you learn more about what is needed.  That is Agile

**Comment by minjupgeorge** [comment]
Yeah that's true. @colevandersWands

**Comment by minjupgeorge** [comment]
#Week 2


## I Need Help With:
So far so good

## What went well?
- Team Work
- Planning
- Communication Plan
- helping Teammates to make them understand how to create PR to solve issues.

## What went less well?
- CSS Boxing styles
- Media Query
-Responsive web page

## Lessons Learned
- To have a good communication with Team mates, conducting meetings on time , Agenda , minutes of meetings are very important as much as coding
- Project is not all about coding . A good Planning and collaboration is the first step for a successful project.

**Comment by colevandersWands** [comment]
@minjupgeorge , have you found the [CSS Games in Chill Zone](https://github.com/lab-brussels-1/home/tree/main/chill-zone#css-games)?  I just noticed those aren't in the suggested study.  

maybe these can help learning CSS

**Comment by danielhalasz** [comment]
@minjupgeorge these CSS tutorials might also be helpful to learn more about CSS grid & flexbox:

Scrimba:
https://scrimba.com/learn/cssgrid
https://scrimba.com/learn/flexbox
https://scrimba.com/learn/cssvariables

Traversy:
https://www.youtube.com/watch?v=0xMQfnTU6oo
https://www.youtube.com/watch?v=3YW65K6LcIA

**Comment by minjupgeorge** [comment]
Week 3

I Need Help With:
So far all good.

What went well?
Communication Plan and User Personas.

What went less well?

Communication between the group members  must be improved. 
I have less time this week for learning since lot of confusions between planning  and working.  Hope everything will be fine since everyone is "agile"

Lessons Learned

Now it's very easy to code html and css but challenging is Teamwork. Anyway its need to be improved. We must be adaptable.

Sunday Prep Work

Started learning bootstrap from website and YouTube videos.

**Comment by danielhalasz** [comment]
@minjupgeorge any specific areas of teamwork that need improvement? can we help in some way?

**Comment by minjupgeorge** [comment]
> 

Thankyou @danielhalasz .As of now we are trying to fix it. Hopefully things will be better.

**Comment by danielhalasz** [comment]
please do not hesitate if it does not, it is always good to try to reflect on it as soon as possible, before it is too late 🙂

**Comment by minjupgeorge** [comment]
> please do not hesitate if it does not, it is always good to try to reflect on it as soon as possible, before it is too late 🙂

Sure. @danielhalasz .Now every one in the team is very exciting to work with bootstrap. compared to documentation , Team collaboration is good now.

**Comment by minjupgeorge** [comment]
## Week 4

## I Need Help With:

Animations in CSS. it is very easy to do carousel using bootstrap 5. Since we have change our website to pure CSS, I have difficulties with animations especially how to use carousel without JavaScript. Please guide me. 

## What went well?

I rebuilt my task in CSS which was made with Bootstrap last week . This time I felt the our team meetings are very short and clear . Every member in the team is so agile that entire code written in bootstrap were rebuilt using pure CSS within a day. 

## What went less well?

First two days I was out of station so I missed team meeting but still managed with summary. Animation part for my task is not complete. still trying my best to resolve it.

## Lesson learned

Don't waste too much time on watching videos rather than trying the code. while trying don't edit it on group repo ,better to try it in the personal repo.

## Sunday Prep Work

I have realized that next week I have to work on the virtual machine . so just started practicing `npm commands` in linux virtual machine.
I have understood the need of `Design Thinking`.

**Comment by minjupgeorge** [comment]
## Me

### What was not clear, where did you get stuck?

 It is not clear for me the animations in the CSS.

Class conventions used in CSS. still our team not having a common rule. I am just trying to UNDERSTAND BEM naming conventions.


### What was clear, what did you master?

- [x] Creating all documents in planning folder.
- [x] Coding HTML 5 using commands and pure CSS.
- [x] CSS: selectors, positioning, grid, flex box and background images
- [x] Bootstrap: Learned and applied well for the task assigned.

### Where can you still use some help?

Animations in CSS without using Java script.

### Where can you help others moving forwards?

Whenever someone pinged and asked , am happy to help them but after sometime i realize that I was stuck up with my task . still I feel hesitate to asked help for completing my task. so it takes so much of my time when I stuck up with error in my code. I know I have to move on quickly .

 ---

## The Course

### What can there be more of?

its good to practice some difficult CSS section during the class time. then it is easy to get help from coaches as well as team mates. 

### What can there be less of?

According to me as of now ,everything is good.

### What material were most helpful (from HYF or elsewhere)?

Materials given by coaches after each session. 

### What HYF material was least helpful?

Everything I find helpful . 

### Any suggestions for future classes?

Its always good to have six members in a group than four members .Rather than small groups ,a group with minimum 5 members is good for information exchange as well as to assign the tasks and complete it on time.

**Comment by minjupgeorge** [comment]
Thankyou @danielhalasz . I will go through it. About virtual machine I have read it here in the settings section.
https://github.com/hackyourfuturebelgium/ux-ui-design

**Comment by danielhalasz** [comment]
@minjupgeorge oh okay, that is just a general instruction included in every module. you can ignore it, especially in the ux/ui module

**Comment by minjupgeorge** [comment]
That's true ..I was thinking that I have wasted so much time on animation but as you said I have learned a lot compared to last week  😄 

Thank you so much @danielhalasz

**Comment by danielhalasz** [comment]
@minjupgeorge you can also look at this for some examples of CSS animation, that can be adapted to your needs:
https://animista.net/
