### ISSUE TITLE
Yea Sung Kim: Agile Development, 4weeks 

### ISSUE THREAD

**Issue by yeasung240** [lab-brussels-1/home#234]
> [my fork of module repository]()
## [0. Developing HTML & CSS](./0-developing-html-and-css)

Practice with the skills, tools, and workflows you will need to efficiently
develop websites written with HTML & CSS.

- 🥚 **VSCode**: you can ...
  - [ ] use the _LiveServer extension_ to launch an HTML page in the browser
  - [ ] use autocomplete to begin a new HTML document, create new tags, and much
        more
  - [ ] use the _HTML CSS Support_ and _IntelliSense fo CSS class names_
        extensions to make writing HTML & CSS more efficient
- 🥚 **Formatting HTML & CSS**: You can ...
  - [ ] use VSCode configurations to format your code on save
  - [ ] use `npm run format` to format all the code in your repository
- [ ] 🥚 **Linting CSS**: You can use the `npm run lint:css` script to find
      mistakes in your CSS, and you can fix the mistakes.
- [ ] 🥚 **Validating HTML**: You can use the `npm run validate:html` script to
      find mistakes in your CSS, and you can fix the mistakes.
- 🥚 **Browser Developer Tools**: You can ...
  - [ ] inspect the source code of a web page using the Sources tab
  - [ ] find any part of the web page in the Elements tab of your Dev Tools DOM
        inspector
  - [ ] find the styles for any element in the Elements tab
  - [ ] make temporary changes in a web page from the Elements tab to see how
        they will look

## [1. Following Plans](./1-following-plans)

Practice working together in a group to build small websites in incremental
steps according to a plan. You will be given final code, a detailed plan to
rebuild it, and will need to work as a group following the processes in
[Planning and Collaborating](https://github.com/HackYourFutureBelgium/planning-and-collaborating).

- [ ] 🥚 **Project Definition and Scope**: As a group, you can agree on what you
      are trying to build, and can clearly describe the project using a README
      and a repository description.
- 🥚 **Project Constraints**: As a group you can define project constraints by
  discussing your strengths, weaknesses and context. You can set these types of
  constraints:
  - [ ] _External_: constraints that come from outside your group
  - [ ] _Internal, Involuntary_: constraints that come from within your group,
        but your group did not decide to have.
  - [ ] _Internal, Voluntary_: constraints your group decides on to improve the
        quality of your development process and final software.
- [ ] 🥚 **Communication Plans**: You can work with your group mates to agree on
      a communication plan to follow during development.
- [ ] 🥚 **Communicating Challenges**: During development you can discuss with
      your group when ...
  - you are blocked and need help the agreed channels of communication.
  - your schedule or availability changes
  - you are having trouble getting along with each other
- [ ] 🥚 **Using a Backlog**: You can develop from a backlog of features
      organized by priority:
  - _must-have_
  - _should-have_
  - _could-have_
- [ ] 🥚 **Follow a Development Strategies**: You can follow a development
      strategy to understand the code required for _must-have_ user stories.
- [ ] 🥚 **Create Issues From a Dev Strategy**: You can create issues for user
      stories in your project based on the development strategy.
- 🥚 **Retrospective**: Your group can complete a retrospective to ...
  - [ ] assess how well you worked as a group
  - [ ] find ways to improve in the next project
  - [ ] compare your plan to the reality of developing your website
- 🐣 **Claiming and Completing Issues**: You can claim issues from the _TODO_
  column of a project board and ...
  - [ ] track your progress with the project board
  - [ ] develop your code locally on a separate branch
  - [ ] send a PR that passes CI checks and meets the requirements
- [ ] 🐣 **Code Review**: You can both review a group mate's PR, and
      productively participate in a review of your own code.
- [ ] 🐣 **Match a Design & Acceptance Criteria**: When developing your tasks,
      you can write code that matches the project's Wireframe and meets your
      issue's Acceptance Criteria.

## [2. Writing Plans](./2-writing-plans)

Practicing writing your own plans as a group. You will be given _only_ the final
code for HTML/CSS web pages, your group will need write a detailed plan for
rebuilding the website in small steps.

- [ ] 🥚 **Write User Personas**: As a group you can describing your site's
      users with User Personas, and you can use the personas to plan your
      website from the user's perspective.
- [ ] 🥚 **Write User Stories**: Given a working web page, you can describe it
      with user stories and acceptance criteria for each user story.
- [ ] 🐣 **Write a Backlog**: After listing all the user stories for a web page,
      you can organize them into a Backlog by priority: _must-have_,
      _should-have_ and _could-have_
- [ ] 🐣 **Create a Prioritized Design**: Using your backlog and the original
      site as a guide, you can create a Wireframe of the site your group will
      build. You can use different colors and comments to indicate a priority
      for each component in the Wireframe.
- [ ] 🐣 **Write a Development Strategies**: You can translate your Wireframe
      and Backlog into a Development Strategy for the _must-have_ user stories.

**Comment by yeasung240** [comment]
## I Need Help With:
- I changed the code by changing the index.html file, But I don't have idea about how to use git to push and pull the code. 

## What went well?
-Communicating with teammates because they are willing to help me all the time.
## What went less well?
-Making the more precise html code. I don't have enough information about it so it is little bit hard to get used to it. 

## Lessons Learned
If I am stuck with hard problem or I have some questions, I have to ask teammate without hesitation. 

## Sunday Prep Work
Learning Java script and understand how to use repository and push code.

**Comment by danielhalasz** [comment]
@yeasung240 we are using the same ideas in terms of git commands as before with markdown, so the only new aspect should be that now it is HTML and CSS files instead. I have shared an interactive git learning tool on Discord and there is a ton of material in the previous module. as mentioned before, each student really needs to put in a lot of time and effort and practice each week, as many parts are not specifically taught on Sunday, such as HTML and CSS, which already has great resources available for studying. What is not available through Youtube videos is how to work as a real-life dev team, so that is what we focus on especially in this module. 

do you have a specific question about git pull or git push that you could not find an answer to after Googling and asking your classmates or coaches?

in the next weeks we will be using the same dev process rebuilding HTML/CSS sites, so you can get more used to it. as you said, communication is key and asking questions is good 😄
