### ISSUE TITLE
Swapna:Welcome to JS

### ISSUE THREAD

**Issue by SWAPNACHEMBOTH** [lab-brussels-1/home#309]
Learning Objectives
all of these skills are limited to short, single-page programs written with Just Enough JavaScript

Priorities: 🥚, 🐣, 🐥, 🐔 (click to learn more)
[1. What is Programming](https://github.com/HackYourFutureBelgium/welcome-to-js/blob/master/1-what-is-programming)
What is a program? What is a programming language? How do programs and people fit together?

- [x]  🥚 Data in, Data Out: You understand that computer programs are used to transform data, and can explain a JS program from this module in terms of the data that goes in and the data that comes out.

- 🥚 Three Audiences: You can explain how a single file of code is used to communicate with 3 different audiences:

- [x]  Developers: You can explain how code formatting, comments, logs and variable names make it easier (or harder!) for a developer to understand a program.

- [x]  Computers: You can explain how a computer follows your instructions to store, read and modify data in program memory.

 

- [x] Users: You can explain how the computer creates a dynamic user experience by following different executions paths depending on user input.

 

- [x] 🥚 Tracing Variables: You can complete a trace table for a program that uses only variables, and can check your work using the "trace" button.

- 🥚 JavaScript Syntax: Given a program, you can identify these parts of JavaScript syntax:

 

- [x] Primitives
- [ ]  Operators
- [ ]  Identifiers
- [ ]  Keywords
- [ ]  Checks
- [ ]  Blocks
- [ ]  Function Calls
- [ ]  🥚 Pseudo Code: You can explain what pseudo code is, how it's used and why it's helpful.
- [ ]  🥚 Program Goals: You understand that a full JavaScript program can be explained as a series of smaller goals, and can write names for the goals in a simple working program.

- 🐣 Program Analysis: You can study a simple working program and identify:

 

- [ ] The program's behavior (data in, data out)
- [ ]  The program's goals
- [ ]  The program's syntax and language features
- [ ]  Which parts of the source code are for which audience (users, devs, computers)
- [ ]  🐥 Same Behavior, Different Code: You can study simple programs with the same behavior (data in, data out) but different source code and explain how the differences matter for each audience.

[2. Just Enough JavaScript](https://github.com/HackYourFutureBelgium/welcome-to-js/blob/master/2-just-enough-javascript)
Go in depth on JavaScript you need to know for writing interactive text-based programs in the browser. Along the way you will learn how each language feature works in small programs.

- 🥚 Listening and Reading: You can read code out loud, and understand your classmates when they read code to you. You don't need to understand how a program works to master these learning objectives!

 

- [ ] Listening You can exactly re-write a program that a classmate has read

 

- [ ] Reading You can read a program out loud and guide your classmates to re-write exactly the same code without them seeing the program. Every indentation, semi-colon, comment and spelling in their program must be identical to yours.

- 🥚 Static vs. Dynamic Analysis: You can explain and use these two ways of studying a program, each can help you understand different aspects of your code. To help understand this concept, the options panel in Study Lenses is organized into static and dynamic study options:

- [ ]  Static: Studying the text in a code file without running it. Some static study methods are creating a flowchart, analyzing variables, filling out a trace table, and drawing on code.

 

- [ ] Dynamic: Running code and studying the computer's behavior. Some dynamic study methods are running code and reading console logs, using the trace button, and stepping through in the debugger or JS Tutor.

 

- [ ] 🥚 Tracing Execution: You can complete a "steps" trace table for all JS language features in Just Enough JavaScript, and can correct your table using console output from the "trace" button.

 

- [ ] 🥚 Analyzing Variables: You can list all the variables in a program, and answer these 5 questions for each variable:

- Where is the variable declared?
- What is the variable's scope?
- Is the variable initialized with a value?
- How many times is its value used (read) in the program?
- How many times is the variable assigned a new value?
- What types are assigned to this variable during the program's execution?

 

- [ ] 🥚 Completing Programs: You can successfully fill in blanks for a program when the missing words are provided, including distractors.
- [ ]  🐣 Translating Pseudo Code: Given a program written in Pseudo Code, you can translate it to working JavaScript.
- [ ]  🐣 Comparing Programs: You can compare two programs with similar code and explain if they have the same behavior or not. If they do not, you can explain how they behave differently and why.
- [ ]  🐥 Constructing Programs: You can reconstruct a program's lines and indentation, successfully ignoring distractor lines.
- [ ]  🐥 Linting: You can find and fix simple linting errors in JavaScript programs.
- [ ]  🐔 Writing Programs: You can write small programs that log specific values, or pass specific test cases.

[3. Understanding Programs](https://github.com/HackYourFutureBelgium/welcome-to-js/blob/master/3-understanding-programs)
Learn how to understand a larger programs by finding connections between the details and the big picture. By the end of this chapter you will know how to read a new program and do a simple code review.

 

- [ ] 🥚 Stepping Through: You can pause a script in a your browser's debugger, arrange the debugger, collapse extra panels, and step through a script written with Just Enough JS. At each point in execution you can make a prediction of the next line before executing, and can check your prediction using the scopes panel.
- [ ]  🥚 Imperative Programming: You can explain what the Imperative Programming paradigm is, and can explain how you know the programs in Welcome to JS are Imperative.
- [ ]  🥚 Logging: You can tracing specific aspects of a program's execution and log them to the console.
- [ ]  🐣 Naming Variables: You can analyze how a variable is used in a program and give it two names:

- Generic: You can give a generic name to a variable based on how it is used in the program.

- Specific: You can give a specific name to a variable based on how it's used and the program's domain (the program's specific data and use-case).

 

- [ ] 🐣 Describing Programs: You can read a program and describe it with comments using to the methodology from /describing-programs:

- Zoom Out
- Zoom In
- Find Connections
- Describe Goals
-  

- [ ] 🐥 Code Review: Given a working program you can review the code for clarity, correctness and style.

[4. Developing Programs](https://github.com/HackYourFutureBelgium/welcome-to-js/blob/master/4-developing-programs)
Learn to modify and write larger programs in JavaScript. You'll cover many of the hidden skills necessary to develop quality software and to work collaboratively on a code base.

 

- [ ] 🥚 Program Life Cycle: You can explain the two phases of a program's life cycle.

Learning Objectives
all of these skills are limited to short, single-page programs written with Just Enough JavaScript

Priorities: 🥚, 🐣, 🐥, 🐔 (click to learn more)
1. What is Programming
What is a program? What is a programming language? How do programs and people fit together?

 🥚 Data in, Data Out: You understand that computer programs are used to transform data, and can explain a JS program from this module in terms of the data that goes in and the data that comes out.
🥚 Three Audiences: You can explain how a single file of code is used to communicate with 3 different audiences:
 Developers: You can explain how code formatting, comments, logs and variable names make it easier (or harder!) for a developer to understand a program.
 Computers: You can explain how a computer follows your instructions to store, read and modify data in program memory.
 Users: You can explain how the computer creates a dynamic user experience by following different executions paths depending on user input.
 🥚 Tracing Variables: You can complete a trace table for a program that uses only variables, and can check your work using the "trace" button.
🥚 JavaScript Syntax: Given a program, you can identify these parts of JavaScript syntax:
 Primitives
 Operators
 Identifiers
 Keywords
 Checks
 Blocks
 Function Calls
 🥚 Pseudo Code: You can explain what pseudo code is, how it's used and why it's helpful.
 🥚 Program Goals: You understand that a full JavaScript program can be explained as a series of smaller goals, and can write names for the goals in a simple working program.
🐣 Program Analysis: You can study a simple working program and identify:
 The program's behavior (data in, data out)
 The program's goals
 The program's syntax and language features
 Which parts of the source code are for which audience (users, devs, computers)
 🐥 Same Behavior, Different Code: You can study simple programs with the same behavior (data in, data out) but different source code and explain how the differences matter for each audience.
2. Just Enough JavaScript
Go in depth on JavaScript you need to know for writing interactive text-based programs in the browser. Along the way you will learn how each language feature works in small programs.

🥚 Listening and Reading: You can read code out loud, and understand your classmates when they read code to you. You don't need to understand how a program works to master these learning objectives!
 Listening You can exactly re-write a program that a classmate has read
 Reading You can read a program out loud and guide your classmates to re-write exactly the same code without them seeing the program. Every indentation, semi-colon, comment and spelling in their program must be identical to yours.
🥚 Static vs. Dynamic Analysis: You can explain and use these two ways of studying a program, each can help you understand different aspects of your code. To help understand this concept, the options panel in Study Lenses is organized into static and dynamic study options:
 Static: Studying the text in a code file without running it. Some static study methods are creating a flowchart, analyzing variables, filling out a trace table, and drawing on code.
 Dynamic: Running code and studying the computer's behavior. Some dynamic study methods are running code and reading console logs, using the trace button, and stepping through in the debugger or JS Tutor.
 🥚 Tracing Execution: You can complete a "steps" trace table for all JS language features in Just Enough JavaScript, and can correct your table using console output from the "trace" button.
 🥚 Analyzing Variables: You can list all the variables in a program, and answer these 5 questions for each variable:
Where is the variable declared?
What is the variable's scope?
Is the variable initialized with a value?
How many times is its value used (read) in the program?
How many times is the variable assigned a new value?
What types are assigned to this variable during the program's execution?
 🥚 Completing Programs: You can successfully fill in blanks for a program when the missing words are provided, including distractors.
 🐣 Translating Pseudo Code: Given a program written in Pseudo Code, you can translate it to working JavaScript.
 🐣 Comparing Programs: You can compare two programs with similar code and explain if they have the same behavior or not. If they do not, you can explain how they behave differently and why.
 🐥 Constructing Programs: You can reconstruct a program's lines and indentation, successfully ignoring distractor lines.
 🐥 Linting: You can find and fix simple linting errors in JavaScript programs.
 🐔 Writing Programs: You can write small programs that log specific values, or pass specific test cases.
3. Understanding Programs
Learn how to understand a larger programs by finding connections between the details and the big picture. By the end of this chapter you will know how to read a new program and do a simple code review.

 🥚 Stepping Through: You can pause a script in a your browser's debugger, arrange the debugger, collapse extra panels, and step through a script written with Just Enough JS. At each point in execution you can make a prediction of the next line before executing, and can check your prediction using the scopes panel.
 🥚 Imperative Programming: You can explain what the Imperative Programming paradigm is, and can explain how you know the programs in Welcome to JS are Imperative.
 🥚 Logging: You can tracing specific aspects of a program's execution and log them to the console.
 🐣 Naming Variables: You can analyze how a variable is used in a program and give it two names:
Generic: You can give a generic name to a variable based on how it is used in the program.
Specific: You can give a specific name to a variable based on how it's used and the program's domain (the program's specific data and use-case).
 🐣 Describing Programs: You can read a program and describe it with comments using to the methodology from /describing-programs:
Zoom Out
Zoom In
Find Connections
Describe Goals
 🐥 Code Review: Given a working program you can review the code for clarity, correctness and style.
4. Developing Programs
Learn to modify and write larger programs in JavaScript. You'll cover many of the hidden skills necessary to develop quality software and to work collaboratively on a code base.

- [ ]  🥚 Program Life Cycle: You can explain the two phases of a program's life cycle.

1. Creation Phase
2. Execution Phase

 

- [ ] 🥚 Fixing Errors: You can use the structured comment to describe an error in your program, and can make several educated guesses at how to fix the error.
- [ ]  🐣 Fixing Bugs: You can use the structured comment to describe and fix a bug in small programs.
- [ ]  🐣 Modifying Programs: You can make small changes in a program to change its behavior without breaking it.
- [ ]  🐥 Refactoring: Given a working program, you can make changes to the code without changing the program's behavior.
- [ ]  🐥 Writing Programs: Given a description of a program's behavior (user story + test cases), you can plan goals for the program and write code to pass the tests.

- 🐔 Reverse Engineering: Given a working program with unreadable code, you can:

- [ ]  Give the program a name.
- [ ]  Describe the program's behavior with a user story, acceptance criteria and test cases.
- [ ]  Plan goals for the program.
- [ ]  Develop your own working program with the exact same behvior.
-

- 🐔 Imagining Programs: Given an empty page, you can imagine and develop your own programs using Just Enough JavaScript. This includes:

 

- [ ] A title.
- [ ]  A description with a user story, acceptance criteria and test cases.
- [ ]  Commented goals.
- [ ]  Fully working Code.

**Comment by danielhalasz** [comment]
@SWAPNACHEMBOTH can you please add your check-in comments for the week and after submitting, add the week-1 label?

**Comment by SWAPNACHEMBOTH** [comment]
Week 1

# I Need Help With:
My dicord App is not working on both mobile & laptop.please help me in resolving it.I can't do anything this week because of  my son had undergone with surgery.Now I am doing all exercises.
# What went well?
variables,syntax,adding comments,let. Doing all exercises and trying to practice with the code.

# Lessons Learned
Going through study materials

# Sunday Prep Work
studying JS

**Comment by SWAPNACHEMBOTH** [comment]
# I Need Help With:


# What went well?


# What went less well?


# Sunday Prep Work

**Comment by danielhalasz** [comment]
@SWAPNACHEMBOTH why did you close the issue?

**Comment by SWAPNACHEMBOTH** [comment]
@danielhalasz, I did till tracing variables.now doing variable- names.Mistakenly I added 2 check-in comments.Tried to deleted that commands apparently issue was closed.

**Comment by danielhalasz** [comment]
> I did till tracing variables.now doing variable- names.

do you mean this part?
http://localhost:4005/1-what-is-programming/03-the-computer/3-variable-names?--defaults

**Comment by SWAPNACHEMBOTH** [comment]
yes,I had done this part.now I am doing
![Screenshot 2022-05-14 at 12 43 31](https://user-images.githubusercontent.com/97672890/168422577-f3f0b1ed-33e4-446c-89ce-6a0e695108e5.png)

**Comment by danielhalasz** [comment]
well, so which one have you done, can you please confirm? in the screenshot you show:
`lesson-plans/computers/1-tracing../examples` which we were doing during the class on Sunday
but the homework this week was to finish and do all of `1-what-is-programming` . have you done any of that?

**Comment by danielhalasz** [comment]
@SWAPNACHEMBOTH

**Comment by SWAPNACHEMBOTH** [comment]
@danielhalasz That was just an example i shown. However what i done was exercises. Adding screenshots here
![Screenshot 2022-05-14 at 22 44 15](https://user-images.githubusercontent.com/97672890/168448187-69df58bb-2af6-471f-8efe-3ac332c32662.png)
![Screenshot 2022-05-14 at 22 53 37](https://user-images.githubusercontent.com/97672890/168448190-476e549e-0af5-4192-a825-39571bfc9e7c.png)
![Screenshot 2022-05-14 at 23 02 39](https://user-images.githubusercontent.com/97672890/168448197-d3d556e4-7720-4129-bfb6-17ba36915124.png)

**Comment by danielhalasz** [comment]
great, good to hear
